# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefile', models.FileField(upload_to='names/')),
                ('textlist', models.TextField()),
            ],
        ),
    ]
