# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namelist',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
