# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0002_namelist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='namelist',
            name='done_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='namelist',
            name='donefile',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='namelist',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
