# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0006_auto_20160827_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namelist',
            name='textlist',
        ),
    ]
