# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0007_remove_namelist_textlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namelist',
            name='done_date',
            field=models.DateTimeField(null=True),
        ),
    ]
