# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsv', '0008_auto_20160903_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namelist',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
